language: cpp

compiler:
  - clang
  - gcc

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libtbb-dev libtbb2

install:
  - cp config/variables.default.inc variables.inc 
  - make
  - export LD_LIBRARY_PATH=$PWD/lib:$LD_LIBRARY_PATH

script: make -C test
