include ../variables.inc
include ../rules.inc

COMMON_SRC = common.cpp data_structures.cpp
COMMON_OBJ = $(subst .cpp,.o, $(COMMON_SRC))

all: $(COMMON_OBJ)


clean:
	rm -rf common.o data_structures.o
